Dv 640 send max
pumapayio/tokenbridge pull request #2
Opened 2021-05-13 12:23 UTC by bajaj6390ankit

This PR include: 
 - Add max button in input field
 - Add click functionality on that button and fill the input box with user balance
 - Update css for responciveness 
 - Test At local and generate PR

2021-05-13 14:41 UTC, kourtellosg requested changes
looks good - please remove logs and we can merge

2021-05-13 14:41 UTC, kourtellosg commented on ui/src/components/NetworkDetails.js
> +  console.log({
remove console log

2021-05-13 14:41 UTC, kourtellosg commented on ui/src/components/NetworkDetails.js
> +    console.log(formattedBalance, totalAmount);
remove log

2021-05-14 11:06 UTC, bajaj6390ankit commented on ui/src/components/NetworkDetails.js
> +  console.log({
removed

2021-05-14 11:06 UTC, bajaj6390ankit commented on ui/src/components/NetworkDetails.js
> +    console.log(formattedBalance, totalAmount);
removed

2021-05-18 05:27 UTC, kourtellosg approved these changes

2021-05-18 05:27 UTC, merged